### ISSUE TITLE
Update luasec to 0.7

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#958]
I wanted to find the minimal dependencies for ZBS. So I created - just for fun - a clean virtual machine with minimal xubuntu-18.04.1-LTS and checked it. What I did on the machine:
```sh
sudo apt install git g++ cmake libgtk2.0-dev libgl1-mesa-dev libglu1-mesa-dev libssl-dev
git clone https://github.com/pkulchenko/ZeroBraneStudio.git
cd ZeroBraneStudio/build
./build-linux.sh all
```
Dependencies I've found
-  `git` `g++` `cmake` : obviously for the build process itself :smile:
- `libgtk2.0-dev` : required to build wxWidgets (this install pulls a huge pack of other -dev packages)
- `libgl1-mesa-dev`, `libglu1-mesa-dev` : required for wxWidgets to configure --with-opengl, which then builds libwx_gtk2u_gl, which is required by wxlua
- `libssl-dev` : required by luasec

BUT: luasec failes to build with several errors. 
```
src/context.c:39:0: warning: "SSLv23_method" redefined
 #define SSLv23_method() TLS_method()
 
In file included from src/context.c:16:0:
/usr/include/openssl/ssl.h:1614:0: note: this is the location of the previous definition
 #define SSLv23_method           TLS_method
 
src/context.c: In function ‘str2method’:
src/context.c:104:3: warning: ‘TLSv1_method’ is deprecated [-Wdeprecated-declarations]
   if (!strcmp(method, "tlsv1"))   return TLSv1_method();
   ^~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from src/context.c:16:
/usr/include/openssl/ssl.h:1624:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
 ^
src/context.c:106:3: warning: ‘TLSv1_1_method’ is deprecated [-Wdeprecated-declarations]
   if (!strcmp(method, "tlsv1_1")) return TLSv1_1_method();
   ^~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from src/context.c:16:
/usr/include/openssl/ssl.h:1630:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_method(void)) /* TLSv1.1 */
 ^
src/context.c:107:3: warning: ‘TLSv1_2_method’ is deprecated [-Wdeprecated-declarations]
   if (!strcmp(method, "tlsv1_2")) return TLSv1_2_method();
   ^~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from src/context.c:16:
/usr/include/openssl/ssl.h:1636:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_method(void)) /* TLSv1.2 */
 ^
src/x509.c: In function ‘push_asn1_string’:
src/x509.c:149:5: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
     lua_pushlstring(L, (char*)ASN1_STRING_data(string),
     ^~~~~~~~~~~~~~~
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from src/x509.c:22:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
src/x509.c: In function ‘push_asn1_ip’:
src/x509.c:185:3: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
   unsigned char *ip = ASN1_STRING_data(string);
   ^~~~~~~~
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from src/x509.c:22:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
src/x509.c: In function ‘meth_extensions’:
src/x509.c:296:35: error: dereferencing pointer to incomplete type ‘X509_EXTENSION {aka struct X509_extension_st}’
     push_asn1_objname(L, extension->object, 1);
                                   ^~
src/x509.c: In function ‘meth_pubkey’:
src/x509.c:407:32: error: dereferencing pointer to incomplete type ‘EVP_PKEY {aka struct evp_pkey_st}’
       switch(EVP_PKEY_type(pkey->type)) {
                                ^~
src/ssl.c: In function ‘meth_getpeercertificate’:
src/ssl.c:464:15: error: dereferencing pointer to incomplete type ‘SSL {aka struct ssl_st}’
   if (ssl->ssl->server)
               ^~
src/ssl.c:474:3: warning: implicit declaration of function ‘CRYPTO_add’; did you mean ‘CRYPTO_free’? [-Wimplicit-function-declaration]
   CRYPTO_add(&cert->references, 1, CRYPTO_LOCK_X509);
   ^~~~~~~~~~
   CRYPTO_free
src/ssl.c:474:19: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
   CRYPTO_add(&cert->references, 1, CRYPTO_LOCK_X509);
                   ^~
src/ssl.c:474:36: error: ‘CRYPTO_LOCK_X509’ undeclared (first use in this function); did you mean ‘CRYPTO_LOCK’?
   CRYPTO_add(&cert->references, 1, CRYPTO_LOCK_X509);
                                    ^~~~~~~~~~~~~~~~
                                    CRYPTO_LOCK
src/ssl.c:474:36: note: each undeclared identifier is reported only once for each function it appears in
src/ssl.c: In function ‘meth_getpeerchain’:
src/ssl.c:506:38: error: ‘CRYPTO_LOCK_X509’ undeclared (first use in this function); did you mean ‘CRYPTO_LOCK’?
     CRYPTO_add(&cert->references, 1, CRYPTO_LOCK_X509);
                                      ^~~~~~~~~~~~~~~~
                                      CRYPTO_LOCK
Error: failed to build LuaSec
```
Then I changed build-linux.sh to
```diff
diff --git a/build/build-linux.sh b/build/build-linux.sh
index 8973afd7..fb9c4fc5 100755
--- a/build/build-linux.sh
+++ b/build/build-linux.sh
@@ -48,7 +48,7 @@ LUASOCKET_BASENAME="luasocket-3.0-rc1"
 LUASOCKET_FILENAME="v3.0-rc1.zip"
 LUASOCKET_URL="https://github.com/diegonehab/luasocket/archive/$LUASOCKET_FILENAME"
 
-LUASEC_BASENAME="luasec-0.6"
+LUASEC_BASENAME="luasec-0.7"
 LUASEC_FILENAME="$LUASEC_BASENAME.zip"
 LUASEC_URL="https://github.com/brunoos/luasec/archive/$LUASEC_FILENAME"
```
and the build passed. :tada:  :cocktail: :tada: :clinking_glasses: 

I didn't test luasec in deep, but I think it should be safe to upgrade zbs to luasec-0.7. Please give it a try.

**Comment by pkulchenko** [comment]
@jjvbsag, thank you for the suggestion; yes, I'll update the build scripts, but the actual binary upgrade will have to wait a bit.

**Comment by pkulchenko** [comment]
@jjvbsag, I got openssl working with the most recent luasec (0.8) and openssl; here is the branch with the Windows binaries and build changes: https://github.com/pkulchenko/ZeroBraneStudio/tree/luasec-0.8-openssl-1.1.1c. I plan to add Linux and macOS changes shortly...

**Comment by jjvbsag** [comment]
@pkulchenko you can close. 
https://github.com/pkulchenko/ZeroBraneStudio/issues/966#issuecomment-550962895 shows, this will be solved in the next release
